[workspace]
members = ["ml_spotitube"]

[package]
name = "in_spotitube"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
librespot = { version = "0.8.0", default-features = false, features = ["native-tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "time"] }

[lib]
crate-type = ["cdylib"]
